### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by mitchcurtis** [Bacon2D/Bacon2D#103]
copy /y E:/Dev/Bacon2D/src/PhysicsEntity.qml E:/Dev/Bacon2D/src/BoxBody.qml E:/Dev/Bacon2D/src/ChainBody.qml E:/Dev/Bacon2D/src/CircleBody.qml E:/Dev/Bacon2D/src/EdgeBody.qml E:/Dev/Bacon2D/src/ImageBoxBody.qml E:/Dev/Bacon2D/src/PolygonBody.qml E:/Dev/Bacon2D/src/Boundaries.qml E:/Dev/Bacon2D/src/RectangleBoxBody.qml E:/Dev/Bacon2D/src/qmldir E:/Dev/Bacon2D-Debug/src/imports/Bacon2D/
    The syntax of the command is incorrect.

I think that the problem is here:

    qmlplugin.commands = $$QMAKE_COPY $$QMLFILES $$OUT_PWD/imports/Bacon2D/
    qmlplugin.path = $$target.path

Windows requires backslashes for its paths, but its copy command also doesn't seem to be able to take multiple files. 

I'm not very good with qmake, but the `INSTALLS` variable as documented [here](http://qt-project.org/doc/qt-4.8/qmake-environment-reference.html#installs) seems to already take care of producing a valid copy command on all supported platforms, so the `.commands` stuff shouldn't be necessary:

    qmlplugin.path = $$target.path
    qmlplugin.files = $$QMLFILES

You might also be able to use the for loop approach shown [here](http://stackoverflow.com/a/3984180/904422) somehow, in combination with [`shell_path`](http://doc.qt.io/qt-5/qmake-function-reference.html#shell-path-path).

**Comment by mitchcurtis** [comment]
I'm also willing to test out potential fixes, or submit them with some guidance. This issues is preventing me from a patch I'm working on for the examples.

**Comment by kenvandine** [comment]
@mitchcurtis I have a branch that may fix this, but I suspect there might be more similar issues.  Please test https://github.com/kenvandine/Bacon2D/tree/windows_qmake

**Comment by kenvandine** [comment]
Thanks for the bug report, should be fixed now.  I've built this on Windows 8.1 with Qt 5.4 and successfully ran some examples.  If you create a game, please share it and your experiences on our G+ community https://plus.google.com/u/0/communities/104485147844809689114

**Comment by mitchcurtis** [comment]
Yep, that fixes it. Thanks. :)
