### ISSUE TITLE
Problem with signals

### ISSUE THREAD

**Issue by 2plus** [Bacon2D/Bacon2D#110]
```
git clone https://github.com/Bacon2D/Bacon2D.git
cd Bacon2D
git submodule update --init

cd 3rdparty/qml-box2d
qmake
mingw32-make
mingw32-make install

cd ..
cd ..

mkdir build && cd build
qmake ..
mingw32-make                // !!!!!!!!!!!!!!!
mingw32-make install
```
![](http://i.imgur.com/Al9d2qi.png)

**Comment by rodrigogolive** [comment]
Hi @2plus,

As a quick fix, you can checkout to this hash (git checkout ad4e5ea52393c9fbf660f0c673e8766ba97875df), until we fix it on master.

Thank you for reporting this issue!

**Comment by kenvandine** [comment]
I have a fix in https://github.com/Bacon2D/Bacon2D/pull/111

**Comment by kenvandine** [comment]
This should be fixed now, please re-open if you still have trouble building on windows.
