### ISSUE TITLE
OSX 10.9.5 and Qt 5.3.2 : could not resolve SDK path for 'macosx10.8'

### ISSUE THREAD

**Issue by ricardodovalle** [Bacon2D/Bacon2D#80]
To solve this issue: `could not resolve SDK path for 'macosx10.8` 
It is necessary to add the bellow code in `Bacon2D.pro` and `src/src.pro` files

```
macx {
    QMAKE_MAC_SDK = macosx10.9
}
```

**Comment by nikolay12** [comment]
@ricardodovalle Where do you execute this:

```
qmake QMAKE_MAC_SDK=macosx10.9
```
?

I tried doing this in a terminal but I am getting:

```
MacBook-Pro$ qmake QMAKE_MAC_SDK=macosx10.10
Usage: qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project
```
It does not seem to work.

**Comment by rodrigogolive** [comment]
Hi, you should add the directory of the pro file. If you have created a 'build' dir and is on it, you should run:
qmake QMAKE_MAC_SDK=macosx10.9 ..

Note the two dots on the end of the command.
Thank you ;)

**Comment by hlawuleka** [comment]
What directory?, it'd be nice to explain as if not everyone already knows what to do.

**Comment by rodrigogolive** [comment]
hi @hlawuleka, assuming you're on Bacon2D repo path:
```
~/Bacon2D $ mkdir build && cd build
~/Bacon2D $ qmake QMAKE_MAC_SDK=OSX_SDK_VERSION ..
```

you can get your OSX_SDK_VERSION by running:
```
xcrun --sdk macosx --show-sdk-version
```

mine is 10.13, so, for me, the last line should be:
```
~/Bacon2D $ qmake QMAKE_MAC_SDK=macosx10.13 ..
```
